### ISSUE TITLE
Unknown person referenced in chapter 8 is PJ Plauger

### ISSUE THREAD

**Issue by aharrison24** [justinmeiners/efficient-programming-with-components#24]
https://en.wikipedia.org/wiki/P._J._Plauger

Notably he wrote the STL implementation (actually the whole C++ standard library) used by Microsoft compilers in the late 90s.

**Comment by justinmeiners** [comment]
Fantastic! Thanks for tracking that down. I have read his C standard library book, but never knew him as "bill".
